"""offline sync ledger (phase 7)

Revision ID: 042c0d9021d4
Revises: 2cfd0deee530
Create Date: 2026-08-20 06:41:37.570001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042c0d9021d4'
down_revision = '2cfd0deee530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_mutations',
    sa.Column('client_mutation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_ref', sa.String(length=160), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("entity_type IN ('ASSESSMENT_SCORE','ATTENDANCE_RECORD')", name=op.f('ck_sync_mutations_entity_type_valid')),
    sa.CheckConstraint("status IN ('APPLIED','REJECTED','CONFLICT')", name=op.f('ck_sync_mutations_status_valid')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_sync_mutations_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_mutations')),
    sa.UniqueConstraint('client_mutation_id', name=op.f('uq_sync_mutations_client_mutation_id'))
    )
    with op.batch_alter_table('sync_mutations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_mutations_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_mutations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_mutations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_mutations_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_mutations_school_id'))

    op.drop_table('sync_mutations')
    # ### end Alembic commands ###
