"""phase 9 performance indexes

Revision ID: 27b4344b50e7
Revises: d53bf9ed970c
Create Date: 2026-08-20 08:05:37.866596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b4344b50e7'
down_revision = 'd53bf9ed970c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollments_year_status', ['academic_year_id', 'status'], unique=False)

    with op.batch_alter_table('fee_charges', schema=None) as batch_op:
        batch_op.create_index('ix_fee_charges_student_status', ['student_id', 'status'], unique=False)

    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_entries_student_term', ['student_id', 'term_id'], unique=False)
        batch_op.create_index('ix_ledger_entries_student_type', ['student_id', 'entry_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_entries_student_type')
        batch_op.drop_index('ix_ledger_entries_student_term')

    with op.batch_alter_table('fee_charges', schema=None) as batch_op:
        batch_op.drop_index('ix_fee_charges_student_status')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollments_year_status')

    # ### end Alembic commands ###
