"""operations engine (phase 6)

Revision ID: 2cfd0deee530
Revises: 51105213e28b
Create Date: 2026-08-20 06:05:35.609232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfd0deee530'
down_revision = '51105213e28b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_criteria',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_appraisal_criteria_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appraisal_criteria')),
    sa.UniqueConstraint('school_id', 'code', name='uq_appraisal_criteria_school_code')
    )
    with op.batch_alter_table('appraisal_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appraisal_criteria_school_id'), ['school_id'], unique=False)

    op.create_table('communication_templates',
    sa.Column('event_code', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("channel IN ('SMS','IN_APP')", name=op.f('ck_communication_templates_channel_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_communication_templates_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_communication_templates_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_communication_templates_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communication_templates')),
    sa.UniqueConstraint('school_id', 'event_code', 'channel', name='uq_comm_templates_event_channel')
    )
    with op.batch_alter_table('communication_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_templates_school_id'), ['school_id'], unique=False)

    op.create_table('discipline_incidents',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('incident_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('staff_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('parent_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("severity IN ('MINOR','MODERATE','SERIOUS')", name=op.f('ck_discipline_incidents_severity_valid')),
    sa.CheckConstraint("status IN ('OPEN','UNDER_REVIEW','RESOLVED')", name=op.f('ck_discipline_incidents_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_discipline_incidents_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_discipline_incidents_school_id_schools')),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], name=op.f('fk_discipline_incidents_staff_user_id_users')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_discipline_incidents_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_discipline_incidents_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discipline_incidents'))
    )
    with op.batch_alter_table('discipline_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discipline_incidents_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discipline_incidents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_discipline_incidents_student_id'), ['student_id'], unique=False)

    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_notifications_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_notifications_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_school_id'), ['school_id'], unique=False)

    op.create_table('pickup_authorizations',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('person_name', sa.String(length=160), nullable=False),
    sa.Column('relationship', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_file_id', sa.Uuid(), nullable=True),
    sa.Column('id_reference', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Uuid(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','REVOKED','EXPIRED')", name=op.f('ck_pickup_authorizations_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pickup_authorizations_created_by_users')),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], name=op.f('fk_pickup_authorizations_revoked_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_pickup_authorizations_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_pickup_authorizations_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_pickup_authorizations_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pickup_authorizations'))
    )
    with op.batch_alter_table('pickup_authorizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_authorizations_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_authorizations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_authorizations_student_id'), ['student_id'], unique=False)

    op.create_table('sms_messages',
    sa.Column('recipient_guardian_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('event_code', sa.String(length=40), nullable=True),
    sa.Column('rendered_body', sa.Text(), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('QUEUED','SENDING','SENT','DELIVERED','FAILED','SKIPPED')", name=op.f('ck_sms_messages_status_valid')),
    sa.ForeignKeyConstraint(['recipient_guardian_id'], ['parent_guardians.id'], name=op.f('fk_sms_messages_recipient_guardian_id_parent_guardians')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_sms_messages_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_sms_messages_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_messages'))
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_messages_recipient_guardian_id'), ['recipient_guardian_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_status'), ['status'], unique=False)

    op.create_table('teacher_appraisals',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('evaluator_user_id', sa.Uuid(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('overall_comment', sa.Text(), nullable=True),
    sa.Column('overall_rating', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','ACKNOWLEDGED')", name=op.f('ck_teacher_appraisals_status_valid')),
    sa.CheckConstraint('period_from <= period_to', name=op.f('ck_teacher_appraisals_period_ordered')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_teacher_appraisals_created_by_users')),
    sa.ForeignKeyConstraint(['evaluator_user_id'], ['users.id'], name=op.f('fk_teacher_appraisals_evaluator_user_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teacher_appraisals_school_id_schools')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_appraisals_teacher_id_teachers')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_teacher_appraisals_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_appraisals'))
    )
    with op.batch_alter_table('teacher_appraisals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_appraisals_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_appraisals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_appraisals_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('appraisal_scores',
    sa.Column('appraisal_id', sa.Uuid(), nullable=False),
    sa.Column('criterion_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['appraisal_id'], ['teacher_appraisals.id'], name=op.f('fk_appraisal_scores_appraisal_id_teacher_appraisals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['criterion_id'], ['appraisal_criteria.id'], name=op.f('fk_appraisal_scores_criterion_id_appraisal_criteria')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_appraisal_scores_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appraisal_scores')),
    sa.UniqueConstraint('appraisal_id', 'criterion_id', name='uq_appraisal_scores_pair')
    )
    with op.batch_alter_table('appraisal_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appraisal_scores_appraisal_id'), ['appraisal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appraisal_scores_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisal_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appraisal_scores_school_id'))
        batch_op.drop_index(batch_op.f('ix_appraisal_scores_appraisal_id'))

    op.drop_table('appraisal_scores')
    with op.batch_alter_table('teacher_appraisals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_appraisals_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_appraisals_status'))
        batch_op.drop_index(batch_op.f('ix_teacher_appraisals_school_id'))

    op.drop_table('teacher_appraisals')
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_messages_status'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_school_id'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_recipient_guardian_id'))

    op.drop_table('sms_messages')
    with op.batch_alter_table('pickup_authorizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pickup_authorizations_student_id'))
        batch_op.drop_index(batch_op.f('ix_pickup_authorizations_status'))
        batch_op.drop_index(batch_op.f('ix_pickup_authorizations_school_id'))

    op.drop_table('pickup_authorizations')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_school_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('discipline_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discipline_incidents_student_id'))
        batch_op.drop_index(batch_op.f('ix_discipline_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_discipline_incidents_school_id'))

    op.drop_table('discipline_incidents')
    with op.batch_alter_table('communication_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_templates_school_id'))

    op.drop_table('communication_templates')
    with op.batch_alter_table('appraisal_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appraisal_criteria_school_id'))

    op.drop_table('appraisal_criteria')
    # ### end Alembic commands ###
