"""core registry (phase 3)

Revision ID: 3195def0910a
Revises: 
Create Date: 2026-08-20 04:00:59.336026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3195def0910a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('previous', sa.JSON(), nullable=True),
    sa.Column('new', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('parent_guardians',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('phone2', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('residential_address', sa.Text(), nullable=True),
    sa.Column('ghana_digital_address', sa.String(length=40), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('comm_preferences', sa.JSON(), nullable=False),
    sa.Column('sms_opt_out', sa.Boolean(), nullable=False),
    sa.Column('photo_file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_parent_guardians_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_parent_guardians_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_parent_guardians_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_guardians'))
    )
    with op.batch_alter_table('parent_guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_guardians_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_guardians_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_guardians_school_id'), ['school_id'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_permissions'))
    )
    op.create_table('schools',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('short_name', sa.String(length=40), nullable=True),
    sa.Column('motto', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ghana_digital_address', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=False),
    sa.Column('logo_file_id', sa.Uuid(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('students',
    sa.Column('admission_code', sa.String(length=24), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('other_names', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=48), nullable=False),
    sa.Column('religion', sa.String(length=48), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admitted_on', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("gender IN ('F','M')", name=op.f('ck_students_gender_valid')),
    sa.CheckConstraint("status IN ('APPLICANT','ADMITTED','ENROLLED','ACTIVE','PROMOTED','REPEATED','WITHDRAWN','TRANSFERRED','SUSPENDED','GRADUATED')", name=op.f('ck_students_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_students_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_students_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_students_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('school_id', 'admission_code', name='uq_students_school_admission_code')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_surname'), ['surname'], unique=False)

    op.create_table('teachers',
    sa.Column('staff_code', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=False),
    sa.Column('other_names', sa.String(length=160), nullable=False),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('qualification', sa.String(length=160), nullable=True),
    sa.Column('job_title', sa.String(length=80), nullable=True),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("employment_status IN ('ACTIVE','ON_LEAVE','EXITED')", name=op.f('ck_teachers_emp_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_teachers_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teachers_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_teachers_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_teachers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('school_id', 'staff_code', name='uq_teachers_school_staff_code'),
    sa.UniqueConstraint('user_id', name=op.f('uq_teachers_user_id'))
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_school_id'), ['school_id'], unique=False)

    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_guardians.id'], name=op.f('fk_users_parent_id_parent_guardians')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_users_student_id_students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_users_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('parent_id', name=op.f('uq_users_parent_id')),
    sa.UniqueConstraint('student_id', name=op.f('uq_users_student_id')),
    sa.UniqueConstraint('teacher_id', name=op.f('uq_users_teacher_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('academic_years',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','ARCHIVED')", name=op.f('ck_academic_years_status_valid')),
    sa.CheckConstraint('starts_on < ends_on', name=op.f('ck_academic_years_dates_ordered')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_academic_years_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_academic_years_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_academic_years_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_years')),
    sa.UniqueConstraint('school_id', 'name', name='uq_academic_years_school_name')
    )
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_years_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_years_status'), ['status'], unique=False)

    op.create_table('departments',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_departments_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('school_id', 'code', name='uq_departments_school_code')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_school_id'), ['school_id'], unique=False)

    op.create_table('document_sequences',
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_document_sequences_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sequences')),
    sa.UniqueConstraint('school_id', 'key', name='uq_document_sequences_school_key')
    )
    op.create_table('parent_student_relationships',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=16), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('is_billing_contact', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("relationship_type IN ('MOTHER','FATHER','GUARDIAN','GRANDPARENT','SIBLING','OTHER')", name=op.f('ck_parent_student_relationships_rel_type_valid')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_parent_student_relationships_confirmed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_parent_student_relationships_created_by_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_guardians.id'], name=op.f('fk_parent_student_relationships_parent_id_parent_guardians')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_parent_student_relationships_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_parent_student_relationships_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_parent_student_relationships_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_student_relationships')),
    sa.UniqueConstraint('parent_id', 'student_id', 'relationship_type', name='uq_parent_student_rel')
    )
    with op.batch_alter_table('parent_student_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_student_relationships_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_relationships_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_relationships_student_id'), ['student_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('roles',
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_roles_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('school_id', 'code', name='uq_roles_school_code')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_school_id'), ['school_id'], unique=False)

    op.create_table('school_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_settings_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_settings')),
    sa.UniqueConstraint('school_id', 'key', name='uq_school_settings_key')
    )
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_settings_school_id'), ['school_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('subjects',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_subjects_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('school_id', 'code', name='uq_subjects_school_code')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_school_id'), ['school_id'], unique=False)

    op.create_table('grades',
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("band IN ('EARLY_CHILDHOOD','PRIMARY','JHS')", name=op.f('ck_grades_band_valid')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_grades_department_id_departments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grades_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grades')),
    sa.UniqueConstraint('school_id', 'code', name='uq_grades_school_code')
    )
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grades_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_grades_school_id'), ['school_id'], unique=False)

    op.create_table('promotion_batches',
    sa.Column('from_academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('to_academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_promotion_batches_created_by_users')),
    sa.ForeignKeyConstraint(['from_academic_year_id'], ['academic_years.id'], name=op.f('fk_promotion_batches_from_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_promotion_batches_school_id_schools')),
    sa.ForeignKeyConstraint(['to_academic_year_id'], ['academic_years.id'], name=op.f('fk_promotion_batches_to_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_promotion_batches_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_batches')),
    sa.UniqueConstraint('from_academic_year_id', 'to_academic_year_id', name='uq_promotion_batches_years')
    )
    with op.batch_alter_table('promotion_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_batches_school_id'), ['school_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_code', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], name=op.f('fk_role_permissions_permission_code_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_code', name=op.f('pk_role_permissions'))
    )
    op.create_table('terms',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.Uuid(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by', sa.Uuid(), nullable=True),
    sa.Column('reopen_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','CLOSED')", name=op.f('ck_terms_status_valid')),
    sa.CheckConstraint('starts_on < ends_on', name=op.f('ck_terms_dates_ordered')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_terms_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_terms_closed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_terms_created_by_users')),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], name=op.f('fk_terms_reopened_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_terms_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_terms_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms')),
    sa.UniqueConstraint('academic_year_id', 'name', name='uq_terms_year_name')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_status'), ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('class_streams',
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('section_label', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_class_streams_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_class_streams_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_class_streams_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_streams')),
    sa.UniqueConstraint('grade_id', 'academic_year_id', 'section_label', name='uq_class_streams_grade_year_section')
    )
    with op.batch_alter_table('class_streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_streams_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_streams_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_streams_school_id'), ['school_id'], unique=False)

    op.create_table('grade_subjects',
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_grade_subjects_grade_id_grades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_grade_subjects_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id', 'subject_id', name=op.f('pk_grade_subjects'))
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_stream_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('is_repeat', sa.Boolean(), nullable=False),
    sa.Column('promotion_decision_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','COMPLETED','WITHDRAWN','TRANSFERRED')", name=op.f('ck_enrollments_status_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_enrollments_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['class_stream_id'], ['class_streams.id'], name=op.f('fk_enrollments_class_stream_id_class_streams')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_enrollments_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_enrollments_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_enrollments_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_enrollments_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_class_stream_id'), ['class_stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    op.create_table('teacher_assignments',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('class_stream_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('SUBJECT_TEACHER','FORM_TEACHER')", name=op.f('ck_teacher_assignments_role_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_teacher_assignments_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['class_stream_id'], ['class_streams.id'], name=op.f('fk_teacher_assignments_class_stream_id_class_streams')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teacher_assignments_school_id_schools')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_assignments_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name=op.f('fk_teacher_assignments_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_assignments'))
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_class_stream_id'), ['class_stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('promotion_decisions',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('from_enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('to_class_stream_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("decision IN ('PROMOTE','REPEAT','WITHDRAW','TRANSFER','GRADUATE')", name=op.f('ck_promotion_decisions_decision_valid')),
    sa.ForeignKeyConstraint(['batch_id'], ['promotion_batches.id'], name=op.f('fk_promotion_decisions_batch_id_promotion_batches')),
    sa.ForeignKeyConstraint(['from_enrollment_id'], ['enrollments.id'], name=op.f('fk_promotion_decisions_from_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_promotion_decisions_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_promotion_decisions_student_id_students')),
    sa.ForeignKeyConstraint(['to_class_stream_id'], ['class_streams.id'], name=op.f('fk_promotion_decisions_to_class_stream_id_class_streams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion_decisions')),
    sa.UniqueConstraint('batch_id', 'student_id', name='uq_promotion_decisions_batch_student')
    )
    with op.batch_alter_table('promotion_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promotion_decisions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promotion_decisions_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_decisions_school_id'))
        batch_op.drop_index(batch_op.f('ix_promotion_decisions_batch_id'))

    op.drop_table('promotion_decisions')
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_school_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_class_stream_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_academic_year_id'))

    op.drop_table('teacher_assignments')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_status'))
        batch_op.drop_index(batch_op.f('ix_enrollments_school_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_class_stream_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_academic_year_id'))

    op.drop_table('enrollments')
    op.drop_table('grade_subjects')
    with op.batch_alter_table('class_streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_streams_school_id'))
        batch_op.drop_index(batch_op.f('ix_class_streams_grade_id'))
        batch_op.drop_index(batch_op.f('ix_class_streams_academic_year_id'))

    op.drop_table('class_streams')
    op.drop_table('user_roles')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_status'))
        batch_op.drop_index(batch_op.f('ix_terms_school_id'))
        batch_op.drop_index(batch_op.f('ix_terms_academic_year_id'))

    op.drop_table('terms')
    op.drop_table('role_permissions')
    with op.batch_alter_table('promotion_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promotion_batches_school_id'))

    op.drop_table('promotion_batches')
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grades_school_id'))
        batch_op.drop_index(batch_op.f('ix_grades_band'))

    op.drop_table('grades')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_school_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('school_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_settings_school_id'))

    op.drop_table('school_settings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_school_id'))

    op.drop_table('roles')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('parent_student_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_student_relationships_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_relationships_school_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_relationships_parent_id'))

    op.drop_table('parent_student_relationships')
    op.drop_table('document_sequences')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_school_id'))

    op.drop_table('departments')
    with op.batch_alter_table('academic_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_years_status'))
        batch_op.drop_index(batch_op.f('ix_academic_years_school_id'))

    op.drop_table('academic_years')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_school_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_surname'))
        batch_op.drop_index(batch_op.f('ix_students_status'))
        batch_op.drop_index(batch_op.f('ix_students_school_id'))

    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('permissions')
    with op.batch_alter_table('parent_guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_guardians_school_id'))
        batch_op.drop_index(batch_op.f('ix_parent_guardians_phone'))
        batch_op.drop_index(batch_op.f('ix_parent_guardians_name'))

    op.drop_table('parent_guardians')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
