"""financial engine (phase 5)

Revision ID: 51105213e28b
Revises: 7859583537f4
Create Date: 2026-08-20 05:30:22.193919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51105213e28b'
down_revision = '7859583537f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('provider_code', sa.String(length=32), nullable=True),
    sa.Column('provider_reference', sa.String(length=96), nullable=True),
    sa.Column('payer_name', sa.String(length=160), nullable=True),
    sa.Column('payer_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("method IN ('MTN_MOMO','TELECEL_CASH','AT_MONEY','CASH','BANK_TRANSFER','OTHER')", name=op.f('ck_payments_method_valid')),
    sa.CheckConstraint("status IN ('INITIATED','PENDING','CONFIRMED','FAILED','REVERSED','REFUNDED')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_payments_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_payments_receipt_id_receipts')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payments_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payments_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_payments_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_payments_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_student_id'), ['student_id'], unique=False)

    op.create_table('receipts',
    sa.Column('receipt_no', sa.String(length=24), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('payer_name', sa.String(length=160), nullable=True),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=False),
    sa.Column('transaction_ref', sa.String(length=96), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('balance_after_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.Uuid(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('pdf_file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('ISSUED','VOIDED')", name=op.f('ck_receipts_status_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_receipts_amount_positive')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_receipts_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_receipts_created_by_users')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_receipts_payment_id_payments')),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['stored_files.id'], name=op.f('fk_receipts_pdf_file_id_stored_files')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_receipts_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_receipts_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_receipts_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_receipts_updated_by_users')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_receipts_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_receipts_payment_id')),
    sa.UniqueConstraint('school_id', 'receipt_no', name='uq_receipts_school_no')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_student_id'), ['student_id'], unique=False)

    op.create_table('payment_provider_configs',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('webhook_secret_env', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind IN ('STUB','LIVE')", name=op.f('ck_payment_provider_configs_kind_valid')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payment_provider_configs_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_provider_configs')),
    sa.UniqueConstraint('school_id', 'code', name='uq_provider_configs_school_code')
    )
    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_provider_configs_school_id'), ['school_id'], unique=False)

    op.create_table('refunds',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('authorized_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('REQUESTED','APPROVED','PAID','REJECTED')", name=op.f('ck_refunds_status_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['authorized_by'], ['users.id'], name=op.f('fk_refunds_authorized_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_refunds_created_by_users')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_refunds_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_refunds_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_refunds_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refunds_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refunds_student_id'), ['student_id'], unique=False)

    op.create_table('webhook_events',
    sa.Column('provider_code', sa.String(length=32), nullable=False),
    sa.Column('external_event_id', sa.String(length=96), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('signature_status', sa.String(length=16), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("signature_status IN ('VALID','INVALID','MISSING')", name=op.f('ck_webhook_events_signature_status_valid')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_webhook_events_payment_id_payments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_webhook_events_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_events_school_id'), ['school_id'], unique=False)

    op.create_table('clearance_policies',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('clearance_type', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.Column('threshold', sa.BigInteger(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('grade_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("clearance_type IN ('REPORT_CARD','EXAMINATION')", name=op.f('ck_clearance_policies_type_valid')),
    sa.CheckConstraint("mode IN ('PERCENT_OF_CHARGES','FIXED_AMOUNT')", name=op.f('ck_clearance_policies_mode_valid')),
    sa.CheckConstraint('threshold >= 0', name=op.f('ck_clearance_policies_threshold_non_negative')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_clearance_policies_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_clearance_policies_created_by_users')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_clearance_policies_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_clearance_policies_school_id_schools')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_clearance_policies_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_clearance_policies_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clearance_policies'))
    )
    with op.batch_alter_table('clearance_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clearance_policies_school_id'), ['school_id'], unique=False)

    op.create_table('fee_structures',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("band IN ('EARLY_CHILDHOOD','PRIMARY','JHS') OR band IS NULL", name=op.f('ck_fee_structures_band_valid')),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','ARCHIVED')", name=op.f('ck_fee_structures_status_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_fee_structures_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fee_structures_created_by_users')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_fee_structures_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_fee_structures_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_fee_structures_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_structures'))
    )
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structures_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structures_school_id'), ['school_id'], unique=False)

    op.create_table('financial_clearances',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('clearance_type', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('override_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('charged_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("state IN ('CLEAR','BLOCKED','WAIVED','PAYMENT_PLAN','PENDING_RECONCILIATION','MANUAL_OVERRIDE')", name=op.f('ck_financial_clearances_state_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_financial_clearances_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_financial_clearances_created_by_users')),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], name=op.f('fk_financial_clearances_override_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_financial_clearances_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_financial_clearances_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_financial_clearances_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_financial_clearances_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_clearances')),
    sa.UniqueConstraint('student_id', 'academic_year_id', 'term_id', 'clearance_type', name='uq_financial_clearances_scope')
    )
    with op.batch_alter_table('financial_clearances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_clearances_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_clearances_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_clearances_student_id'), ['student_id'], unique=False)

    op.create_table('fee_structure_items',
    sa.Column('structure_id', sa.Uuid(), nullable=False),
    sa.Column('fee_type', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("fee_type IN ('TUITION','FEEDING','ICT_LAB','PTA_LEVY','TRANSPORT','EXAMINATION','OTHER')", name=op.f('ck_fee_structure_items_fee_type_valid')),
    sa.CheckConstraint("period IN ('PER_TERM','PER_YEAR','ONE_OFF')", name=op.f('ck_fee_structure_items_period_valid')),
    sa.CheckConstraint('amount_pesewas >= 0', name=op.f('ck_fee_structure_items_amount_non_negative')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_fee_structure_items_school_id_schools')),
    sa.ForeignKeyConstraint(['structure_id'], ['fee_structures.id'], name=op.f('fk_fee_structure_items_structure_id_fee_structures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_fee_structure_items_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_structure_items'))
    )
    with op.batch_alter_table('fee_structure_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_structure_items_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_structure_items_structure_id'), ['structure_id'], unique=False)

    op.create_table('fee_charges',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('fee_type', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("source IN ('STRUCTURE','MANUAL','OPENING')", name=op.f('ck_fee_charges_source_valid')),
    sa.CheckConstraint("status IN ('ACTIVE','PART_SETTLED','SETTLED','ADJUSTED')", name=op.f('ck_fee_charges_status_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_fee_charges_amount_positive')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_fee_charges_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_fee_charges_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_fee_charges_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_fee_charges_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_fee_charges_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_fee_charges_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_fee_charges_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fee_charges'))
    )
    with op.batch_alter_table('fee_charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_charges_academic_year_id'), ['academic_year_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_charges_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_charges_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_charges_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fee_charges_student_id'), ['student_id'], unique=False)

    op.create_table('payment_plans',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('PROPOSED','APPROVED','ON_TRACK','DEFAULTED','COMPLETED')", name=op.f('ck_payment_plans_status_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_payment_plans_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payment_plans_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_payment_plans_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payment_plans_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_payment_plans_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_payment_plans_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_payment_plans_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_plans'))
    )
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plans_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plans_student_id'), ['student_id'], unique=False)

    op.create_table('adjustments',
    sa.Column('fee_charge_id', sa.Uuid(), nullable=True),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("direction IN ('DEBIT','CREDIT')", name=op.f('ck_adjustments_direction_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_adjustments_amount_positive')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_adjustments_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_adjustments_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_adjustments_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['fee_charge_id'], ['fee_charges.id'], name=op.f('fk_adjustments_fee_charge_id_fee_charges')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_adjustments_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_adjustments_student_id_students')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_adjustments_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustments'))
    )
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adjustments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adjustments_student_id'), ['student_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('fee_charge_id', sa.Uuid(), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_payment_allocations_amount_positive')),
    sa.ForeignKeyConstraint(['fee_charge_id'], ['fee_charges.id'], name=op.f('fk_payment_allocations_fee_charge_id_fee_charges')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_allocations_payment_id_payments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payment_allocations_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_fee_charge_id'), ['fee_charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_school_id'), ['school_id'], unique=False)

    op.create_table('payment_plan_installments',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PAID','MISSED')", name=op.f('ck_payment_plan_installments_status_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_payment_plan_installments_amount_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['payment_plans.id'], name=op.f('fk_payment_plan_installments_plan_id_payment_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_payment_plan_installments_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_plan_installments'))
    )
    with op.batch_alter_table('payment_plan_installments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plan_installments_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_plan_installments_school_id'), ['school_id'], unique=False)

    op.create_table('waivers',
    sa.Column('fee_charge_id', sa.Uuid(), nullable=True),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=True),
    sa.Column('pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("kind IN ('WAIVER','DISCOUNT','SCHOLARSHIP')", name=op.f('ck_waivers_kind_valid')),
    sa.CheckConstraint('(amount_pesewas IS NOT NULL) != (pct IS NOT NULL)', name=op.f('ck_waivers_exactly_one_of_amount_pct')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_waivers_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_waivers_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_waivers_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['fee_charge_id'], ['fee_charges.id'], name=op.f('fk_waivers_fee_charge_id_fee_charges')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_waivers_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_waivers_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_waivers_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_waivers_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waivers'))
    )
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waivers_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waivers_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waivers_student_id'), ['student_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('amount_pesewas', sa.BigInteger(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fee_charge_id', sa.Uuid(), nullable=True),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('waiver_id', sa.Uuid(), nullable=True),
    sa.Column('adjustment_id', sa.Uuid(), nullable=True),
    sa.Column('refund_id', sa.Uuid(), nullable=True),
    sa.Column('reversed_entry_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=96), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("category IN ('CHARGE','PAYMENT','WAIVER','ADJUSTMENT','REFUND','CREDIT_NOTE','OPENING_BALANCE','REVERSAL')", name=op.f('ck_ledger_entries_category_valid')),
    sa.CheckConstraint("entry_type IN ('DEBIT','CREDIT')", name=op.f('ck_ledger_entries_entry_type_valid')),
    sa.CheckConstraint('amount_pesewas > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_ledger_entries_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['adjustment_id'], ['adjustments.id'], name=op.f('fk_ledger_entries_adjustment_id_adjustments')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_entries_created_by_users')),
    sa.ForeignKeyConstraint(['fee_charge_id'], ['fee_charges.id'], name=op.f('fk_ledger_entries_fee_charge_id_fee_charges')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_ledger_entries_payment_id_payments')),
    sa.ForeignKeyConstraint(['refund_id'], ['refunds.id'], name=op.f('fk_ledger_entries_refund_id_refunds')),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['ledger_entries.id'], name=op.f('fk_ledger_entries_reversed_entry_id_ledger_entries')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_ledger_entries_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_ledger_entries_student_id_students')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_ledger_entries_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_ledger_entries_updated_by_users')),
    sa.ForeignKeyConstraint(['waiver_id'], ['waivers.id'], name=op.f('fk_ledger_entries_waiver_id_waivers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_ledger_entries_idempotency_key'))
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_student_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_school_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waivers_student_id'))
        batch_op.drop_index(batch_op.f('ix_waivers_school_id'))
        batch_op.drop_index(batch_op.f('ix_waivers_enrollment_id'))

    op.drop_table('waivers')
    with op.batch_alter_table('payment_plan_installments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plan_installments_school_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plan_installments_plan_id'))

    op.drop_table('payment_plan_installments')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_school_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_fee_charge_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adjustments_student_id'))
        batch_op.drop_index(batch_op.f('ix_adjustments_school_id'))

    op.drop_table('adjustments')
    with op.batch_alter_table('payment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plans_student_id'))
        batch_op.drop_index(batch_op.f('ix_payment_plans_school_id'))

    op.drop_table('payment_plans')
    with op.batch_alter_table('fee_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_charges_student_id'))
        batch_op.drop_index(batch_op.f('ix_fee_charges_status'))
        batch_op.drop_index(batch_op.f('ix_fee_charges_school_id'))
        batch_op.drop_index(batch_op.f('ix_fee_charges_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_fee_charges_academic_year_id'))

    op.drop_table('fee_charges')
    with op.batch_alter_table('fee_structure_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structure_items_structure_id'))
        batch_op.drop_index(batch_op.f('ix_fee_structure_items_school_id'))

    op.drop_table('fee_structure_items')
    with op.batch_alter_table('financial_clearances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_clearances_student_id'))
        batch_op.drop_index(batch_op.f('ix_financial_clearances_state'))
        batch_op.drop_index(batch_op.f('ix_financial_clearances_school_id'))

    op.drop_table('financial_clearances')
    with op.batch_alter_table('fee_structures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_structures_school_id'))
        batch_op.drop_index(batch_op.f('ix_fee_structures_academic_year_id'))

    op.drop_table('fee_structures')
    with op.batch_alter_table('clearance_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clearance_policies_school_id'))

    op.drop_table('clearance_policies')
    with op.batch_alter_table('webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_events_school_id'))

    op.drop_table('webhook_events')
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refunds_student_id'))
        batch_op.drop_index(batch_op.f('ix_refunds_school_id'))

    op.drop_table('refunds')
    with op.batch_alter_table('payment_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_provider_configs_school_id'))

    op.drop_table('payment_provider_configs')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_student_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_school_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_student_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_school_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
