"""academic engine (phase 4)

Revision ID: 7859583537f4
Revises: 3195def0910a
Create Date: 2026-08-20 05:03:01.788329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7859583537f4'
down_revision = '3195def0910a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_competencies',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_core_competencies_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_core_competencies')),
    sa.UniqueConstraint('school_id', 'code', name='uq_core_competencies_school_code')
    )
    with op.batch_alter_table('core_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_competencies_school_id'), ['school_id'], unique=False)

    op.create_table('curricula',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("origin IN ('NATIONAL','SCHOOL')", name=op.f('ck_curricula_origin_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_curricula_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_curricula_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_curricula_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curricula')),
    sa.UniqueConstraint('school_id', 'name', name='uq_curricula_school_name')
    )
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curricula_school_id'), ['school_id'], unique=False)

    op.create_table('developmental_domains',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_developmental_domains_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developmental_domains')),
    sa.UniqueConstraint('school_id', 'code', name='uq_developmental_domains_school_code')
    )
    with op.batch_alter_table('developmental_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developmental_domains_school_id'), ['school_id'], unique=False)

    op.create_table('report_templates',
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("band IN ('EARLY_CHILDHOOD','PRIMARY','JHS')", name=op.f('ck_report_templates_band_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_templates_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_report_templates_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_report_templates_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_templates')),
    sa.UniqueConstraint('school_id', 'band', 'version', name='uq_report_templates_band_version')
    )
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_templates_school_id'), ['school_id'], unique=False)

    op.create_table('stored_files',
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stored_files_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_stored_files_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_stored_files_storage_key'))
    )
    op.create_table('curriculum_versions',
    sa.Column('curriculum_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=32), nullable=False),
    sa.Column('effective_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','PUBLISHED','ARCHIVED')", name=op.f('ck_curriculum_versions_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_curriculum_versions_created_by_users')),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], name=op.f('fk_curriculum_versions_curriculum_id_curricula')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_curriculum_versions_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_curriculum_versions_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_versions')),
    sa.UniqueConstraint('curriculum_id', 'version_label', name='uq_cv_curriculum_label')
    )
    with op.batch_alter_table('curriculum_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curriculum_versions_curriculum_id'), ['curriculum_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curriculum_versions_status'), ['status'], unique=False)

    op.create_table('assessment_schemes',
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_assessment_schemes_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assessment_schemes_created_by_users')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_assessment_schemes_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_assessment_schemes_school_id_schools')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_assessment_schemes_subject_id_subjects')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_assessment_schemes_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_assessment_schemes_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_schemes')),
    sa.UniqueConstraint('academic_year_id', 'term_id', 'grade_id', 'subject_id', name='uq_assessment_schemes_scope')
    )
    with op.batch_alter_table('assessment_schemes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_schemes_school_id'), ['school_id'], unique=False)

    op.create_table('grade_scales',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('scope_band', sa.String(length=16), nullable=True),
    sa.Column('grade_id', sa.Uuid(), nullable=True),
    sa.Column('academic_year_id', sa.Uuid(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("scope_band IN ('EARLY_CHILDHOOD','PRIMARY','JHS') OR scope_band IS NULL", name=op.f('ck_grade_scales_band_valid')),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('fk_grade_scales_academic_year_id_academic_years')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_grade_scales_created_by_users')),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_grade_scales_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grade_scales_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_grade_scales_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_scales'))
    )
    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_scales_school_id'), ['school_id'], unique=False)

    op.create_table('report_cards',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('clearance_snapshot', sa.JSON(), nullable=True),
    sa.Column('pdf_file_id', sa.Uuid(), nullable=True),
    sa.Column('teacher_remark', sa.Text(), nullable=True),
    sa.Column('head_remark', sa.Text(), nullable=True),
    sa.Column('finalized_by', sa.Uuid(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','GENERATED','FINALIZED','PUBLISHED')", name=op.f('ck_report_cards_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_report_cards_created_by_users')),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], name=op.f('fk_report_cards_finalized_by_users')),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['stored_files.id'], name=op.f('fk_report_cards_pdf_file_id_stored_files')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_report_cards_school_id_schools')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_report_cards_student_id_students')),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], name=op.f('fk_report_cards_template_id_report_templates')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_report_cards_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_report_cards_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_cards')),
    sa.UniqueConstraint('student_id', 'term_id', name='uq_report_cards_student_term')
    )
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_cards_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_cards_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_cards_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_cards_term_id'), ['term_id'], unique=False)

    op.create_table('strands',
    sa.Column('curriculum_version_id', sa.Uuid(), nullable=False),
    sa.Column('grade_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_version_id'], ['curriculum_versions.id'], name=op.f('fk_strands_curriculum_version_id_curriculum_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_strands_grade_id_grades')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_strands_school_id_schools')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_strands_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strands')),
    sa.UniqueConstraint('curriculum_version_id', 'grade_id', 'subject_id', 'code', name='uq_strands_version_grade_subject_code')
    )
    with op.batch_alter_table('strands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strands_curriculum_version_id'), ['curriculum_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strands_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_components',
    sa.Column('scheme_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('aggregation', sa.String(length=16), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("aggregation IN ('DIRECT','MEAN','BEST')", name=op.f('ck_assessment_components_aggregation_valid')),
    sa.CheckConstraint("kind IN ('CLASS','EXAM')", name=op.f('ck_assessment_components_kind_valid')),
    sa.CheckConstraint('max_score > 0', name=op.f('ck_assessment_components_max_positive')),
    sa.CheckConstraint('weight_pct > 0 AND weight_pct <= 100', name=op.f('ck_assessment_components_weight_range')),
    sa.ForeignKeyConstraint(['scheme_id'], ['assessment_schemes.id'], name=op.f('fk_assessment_components_scheme_id_assessment_schemes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_assessment_components_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_components')),
    sa.UniqueConstraint('scheme_id', 'code', name='uq_assessment_components_scheme_code')
    )
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_components_scheme_id'), ['scheme_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_components_school_id'), ['school_id'], unique=False)

    op.create_table('attendance_sheets',
    sa.Column('class_stream_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_date', sa.Date(), nullable=False),
    sa.Column('taken_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED')", name=op.f('ck_attendance_sheets_status_valid')),
    sa.ForeignKeyConstraint(['class_stream_id'], ['class_streams.id'], name=op.f('fk_attendance_sheets_class_stream_id_class_streams')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_attendance_sheets_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_attendance_sheets_school_id_schools')),
    sa.ForeignKeyConstraint(['taken_by'], ['users.id'], name=op.f('fk_attendance_sheets_taken_by_users')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_attendance_sheets_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_attendance_sheets_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sheets')),
    sa.UniqueConstraint('class_stream_id', 'sheet_date', name='uq_attendance_sheets_class_date')
    )
    with op.batch_alter_table('attendance_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sheets_class_stream_id'), ['class_stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sheets_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sheets_term_id'), ['term_id'], unique=False)

    op.create_table('grade_scale_bands',
    sa.Column('scale_id', sa.Uuid(), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('remark', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('min_score <= max_score', name=op.f('ck_grade_scale_bands_range_ordered')),
    sa.ForeignKeyConstraint(['scale_id'], ['grade_scales.id'], name=op.f('fk_grade_scale_bands_scale_id_grade_scales'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_grade_scale_bands_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grade_scale_bands'))
    )
    with op.batch_alter_table('grade_scale_bands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grade_scale_bands_scale_id'), ['scale_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grade_scale_bands_school_id'), ['school_id'], unique=False)

    op.create_table('sub_strands',
    sa.Column('strand_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_sub_strands_school_id_schools')),
    sa.ForeignKeyConstraint(['strand_id'], ['strands.id'], name=op.f('fk_sub_strands_strand_id_strands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_strands')),
    sa.UniqueConstraint('strand_id', 'code', name='uq_sub_strands_strand_code')
    )
    with op.batch_alter_table('sub_strands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_strands_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sub_strands_strand_id'), ['strand_id'], unique=False)

    op.create_table('assessments',
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('class_stream_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','LOCKED')", name=op.f('ck_assessments_status_valid')),
    sa.ForeignKeyConstraint(['class_stream_id'], ['class_streams.id'], name=op.f('fk_assessments_class_stream_id_class_streams')),
    sa.ForeignKeyConstraint(['component_id'], ['assessment_components.id'], name=op.f('fk_assessments_component_id_assessment_components')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_assessments_created_by_users')),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name=op.f('fk_assessments_locked_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_assessments_school_id_schools')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_assessments_subject_id_subjects')),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_assessments_submitted_by_users')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_assessments_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_assessments_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessments')),
    sa.UniqueConstraint('term_id', 'class_stream_id', 'subject_id', 'component_id', name='uq_assessments_scope')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_class_stream_id'), ['class_stream_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_term_id'), ['term_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("status IN ('PRESENT','ABSENT','LATE','EXCUSED','LEFT_EARLY')", name=op.f('ck_attendance_records_status_valid')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_attendance_records_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_attendance_records_school_id_schools')),
    sa.ForeignKeyConstraint(['sheet_id'], ['attendance_sheets.id'], name=op.f('fk_attendance_records_sheet_id_attendance_sheets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('sheet_id', 'enrollment_id', name='uq_attendance_records_pair')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_sheet_id'), ['sheet_id'], unique=False)

    op.create_table('competency_ratings',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("rating IN ('EMERGING','DEVELOPING','ACHIEVED')", name=op.f('ck_competency_ratings_rating_valid')),
    sa.ForeignKeyConstraint(['competency_id'], ['core_competencies.id'], name=op.f('fk_competency_ratings_competency_id_core_competencies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_competency_ratings_created_by_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_competency_ratings_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_competency_ratings_school_id_schools')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_competency_ratings_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_competency_ratings_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competency_ratings')),
    sa.UniqueConstraint('enrollment_id', 'term_id', 'competency_id', name='uq_competency_ratings_unique')
    )
    with op.batch_alter_table('competency_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_ratings_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_ratings_school_id'), ['school_id'], unique=False)

    op.create_table('content_standards',
    sa.Column('sub_strand_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_content_standards_school_id_schools')),
    sa.ForeignKeyConstraint(['sub_strand_id'], ['sub_strands.id'], name=op.f('fk_content_standards_sub_strand_id_sub_strands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_standards')),
    sa.UniqueConstraint('sub_strand_id', 'code', name='uq_content_standards_sub_strand_code')
    )
    with op.batch_alter_table('content_standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_standards_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_standards_sub_strand_id'), ['sub_strand_id'], unique=False)

    op.create_table('developmental_ratings',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('domain_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("rating IN ('EMERGING','DEVELOPING','ACHIEVED')", name=op.f('ck_developmental_ratings_rating_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_developmental_ratings_created_by_users')),
    sa.ForeignKeyConstraint(['domain_id'], ['developmental_domains.id'], name=op.f('fk_developmental_ratings_domain_id_developmental_domains')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_developmental_ratings_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_developmental_ratings_school_id_schools')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_developmental_ratings_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_developmental_ratings_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_developmental_ratings')),
    sa.UniqueConstraint('enrollment_id', 'term_id', 'domain_id', name='uq_developmental_ratings_unique')
    )
    with op.batch_alter_table('developmental_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_developmental_ratings_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_developmental_ratings_school_id'), ['school_id'], unique=False)

    op.create_table('observation_logs',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_observation_logs_author_user_id_users')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_observation_logs_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_observation_logs_school_id_schools')),
    sa.ForeignKeyConstraint(['superseded_by'], ['observation_logs.id'], name=op.f('fk_observation_logs_superseded_by_observation_logs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_logs'))
    )
    with op.batch_alter_table('observation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_logs_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_logs_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_scores',
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('raw_score >= 0', name=op.f('ck_assessment_scores_score_non_negative')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('fk_assessment_scores_assessment_id_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_assessment_scores_enrollment_id_enrollments')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_assessment_scores_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_scores')),
    sa.UniqueConstraint('assessment_id', 'enrollment_id', name='uq_assessment_scores_pair')
    )
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_scores_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_scores_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_scores_school_id'), ['school_id'], unique=False)

    op.create_table('indicators',
    sa.Column('content_standard_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_standard_id'], ['content_standards.id'], name=op.f('fk_indicators_content_standard_id_content_standards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_indicators_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators')),
    sa.UniqueConstraint('content_standard_id', 'code', name='uq_indicators_content_standard_code')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_content_standard_id'), ['content_standard_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_school_id'), ['school_id'], unique=False)

    op.create_table('indicator_core_competencies',
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('competency_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['core_competencies.id'], name=op.f('fk_indicator_core_competencies_competency_id_core_competencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], name=op.f('fk_indicator_core_competencies_indicator_id_indicators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('indicator_id', 'competency_id', name=op.f('pk_indicator_core_competencies'))
    )
    op.create_table('score_overrides',
    sa.Column('assessment_score_id', sa.Uuid(), nullable=False),
    sa.Column('original_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_score_overrides_approved_by_users')),
    sa.ForeignKeyConstraint(['assessment_score_id'], ['assessment_scores.id'], name=op.f('fk_score_overrides_assessment_score_id_assessment_scores')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_score_overrides_requested_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_score_overrides_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_overrides'))
    )
    with op.batch_alter_table('score_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_overrides_assessment_score_id'), ['assessment_score_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_overrides_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_overrides_school_id'))
        batch_op.drop_index(batch_op.f('ix_score_overrides_assessment_score_id'))

    op.drop_table('score_overrides')
    op.drop_table('indicator_core_competencies')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_school_id'))
        batch_op.drop_index(batch_op.f('ix_indicators_content_standard_id'))

    op.drop_table('indicators')
    with op.batch_alter_table('assessment_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_scores_school_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_scores_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_scores_assessment_id'))

    op.drop_table('assessment_scores')
    with op.batch_alter_table('observation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_logs_school_id'))
        batch_op.drop_index(batch_op.f('ix_observation_logs_enrollment_id'))

    op.drop_table('observation_logs')
    with op.batch_alter_table('developmental_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developmental_ratings_school_id'))
        batch_op.drop_index(batch_op.f('ix_developmental_ratings_enrollment_id'))

    op.drop_table('developmental_ratings')
    with op.batch_alter_table('content_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_standards_sub_strand_id'))
        batch_op.drop_index(batch_op.f('ix_content_standards_school_id'))

    op.drop_table('content_standards')
    with op.batch_alter_table('competency_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_ratings_school_id'))
        batch_op.drop_index(batch_op.f('ix_competency_ratings_enrollment_id'))

    op.drop_table('competency_ratings')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_school_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_enrollment_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_term_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_school_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_class_stream_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('sub_strands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_strands_strand_id'))
        batch_op.drop_index(batch_op.f('ix_sub_strands_school_id'))

    op.drop_table('sub_strands')
    with op.batch_alter_table('grade_scale_bands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_scale_bands_school_id'))
        batch_op.drop_index(batch_op.f('ix_grade_scale_bands_scale_id'))

    op.drop_table('grade_scale_bands')
    with op.batch_alter_table('attendance_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sheets_term_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sheets_school_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sheets_class_stream_id'))

    op.drop_table('attendance_sheets')
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_components_school_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_components_scheme_id'))

    op.drop_table('assessment_components')
    with op.batch_alter_table('strands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strands_school_id'))
        batch_op.drop_index(batch_op.f('ix_strands_curriculum_version_id'))

    op.drop_table('strands')
    with op.batch_alter_table('report_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_cards_term_id'))
        batch_op.drop_index(batch_op.f('ix_report_cards_student_id'))
        batch_op.drop_index(batch_op.f('ix_report_cards_status'))
        batch_op.drop_index(batch_op.f('ix_report_cards_school_id'))

    op.drop_table('report_cards')
    with op.batch_alter_table('grade_scales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grade_scales_school_id'))

    op.drop_table('grade_scales')
    with op.batch_alter_table('assessment_schemes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_schemes_school_id'))

    op.drop_table('assessment_schemes')
    with op.batch_alter_table('curriculum_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_status'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_school_id'))
        batch_op.drop_index(batch_op.f('ix_curriculum_versions_curriculum_id'))

    op.drop_table('curriculum_versions')
    op.drop_table('stored_files')
    with op.batch_alter_table('report_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_templates_school_id'))

    op.drop_table('report_templates')
    with op.batch_alter_table('developmental_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_developmental_domains_school_id'))

    op.drop_table('developmental_domains')
    with op.batch_alter_table('curricula', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curricula_school_id'))

    op.drop_table('curricula')
    with op.batch_alter_table('core_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_competencies_school_id'))

    op.drop_table('core_competencies')
    # ### end Alembic commands ###
