"""bulk imports (phase 8)

Revision ID: d53bf9ed970c
Revises: 042c0d9021d4
Create Date: 2026-08-20 07:38:58.377303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53bf9ed970c'
down_revision = '042c0d9021d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('rows_warn', sa.Integer(), nullable=False),
    sa.Column('rows_error', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('rows_match', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("kind IN ('STUDENTS','TEACHERS','PARENTS')", name=op.f('ck_import_jobs_kind_valid')),
    sa.CheckConstraint("stage IN ('UPLOADED','PARSED','PREVIEWED','CONFIRMED','IMPORTING','COMPLETED','FAILED','ROLLED_BACK')", name=op.f('ck_import_jobs_stage_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_jobs_created_by_users')),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], name=op.f('fk_import_jobs_file_id_stored_files')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_import_jobs_school_id_schools')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_import_jobs_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_jobs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_jobs_stage'), ['stage'], unique=False)

    op.create_table('import_errors',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('match_suggestion', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("severity IN ('OK','WARNING','ERROR','DUPLICATE','MATCH_CANDIDATE')", name=op.f('ck_import_errors_severity_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['import_jobs.id'], name=op.f('fk_import_errors_job_id_import_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_import_errors_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_errors'))
    )
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_errors_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_errors_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_errors_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_errors_severity'))
        batch_op.drop_index(batch_op.f('ix_import_errors_school_id'))
        batch_op.drop_index(batch_op.f('ix_import_errors_job_id'))

    op.drop_table('import_errors')
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_jobs_stage'))
        batch_op.drop_index(batch_op.f('ix_import_jobs_school_id'))

    op.drop_table('import_jobs')
    # ### end Alembic commands ###
